# Use a imagem base Ubuntu
FROM ubuntu:latest

# Atualize a lista de pacotes e instale dependências necessárias (Python, logger)
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# Copiar o script Python para o contêiner
COPY proxy.py /usr/local/bin/enviar_log.py

# Definir o diretório de trabalho
WORKDIR /usr/local/bin

EXPOSE 8888

# Comando para rodar o script Python
CMD ["python3", "/usr/local/bin/proxy.py"]

# Manter o contêiner em execução com uma interação contínua
# CMD ["tail", "-f", "/dev/null"]